/**
 * Tokens de cores depreciados.
 */
 export default [
    { key: 'colors.brand', type: 'token' },
    { key: 'colors.university', type: 'token' },
    { key: 'colors.external', type: 'token' },
    { key: '#00ac4a', type: 'cor' },
    { key: '#bdebcc', type: 'cor' },
    { key: '#8fdeac', type: 'cor' },
    { key: '#58d289', type: 'cor' },
    { key: '#11c76f', type: 'cor' },
    { key: '#00bc54', type: 'cor' },
    { key: '#00984b', type: 'cor' },
    { key: '#008441', type: 'cor' },
    { key: '#006532', type: 'cor' },
    { key: '#d9f3fa', type: 'cor' },
    { key: '#bbdde1', type: 'cor' },
    { key: '#9ac3ca', type: 'cor' },
    { key: '#78a9b1', type: 'cor' },
    { key: '#5e959e', type: 'cor' },
    { key: '#43828c', type: 'cor' },
    { key: '#38727c', type: 'cor' },
    { key: '#295e67', type: 'cor' },
    { key: '#1c4b53', type: 'cor' },
    { key: '#0a353c', type: 'cor' },
    { key: '#fef8e3', type: 'cor' },
    { key: '#fcdf8b', type: 'cor' },
    { key: '#fac942', type: 'cor' },
    { key: '#f8b330', type: 'cor' },
    { key: '#f37422', type: 'cor' },
    { key: '#ffe6eb', type: 'cor' },
    { key: '#ff96ae', type: 'cor' },
    { key: '#ff4f75', type: 'cor' },
    { key: '#ff2048', type: 'cor' },
    { key: '#ff0828', type: 'cor' },
    { key: '#f37422', type: 'cor' },
    { key: '#e0f4fc', type: 'cor' },
    { key: '#7bd1f4', type: 'cor' },
    { key: '#00b0ed', type: 'cor' },
    { key: '#0097dc', type: 'cor' },
    { key: '#0073b5', type: 'cor' },
    { key: '#f2f2f2', type: 'cor' },
    { key: '#e5e5e5', type: 'cor' },
    { key: '#aab0b2', type: 'cor' },
    { key: '#8a9499', type: 'cor' },
    { key: '#6c7980', type: 'cor' },
    { key: '#525f66', type: 'cor' },
    { key: '#39464d', type: 'cor' },
    { key: '#212d33', type: 'cor' },
    { key: '#0e161a', type: 'cor' },
    { key: '#c1c9ed', type: 'cor' },
    { key: '#6a84d6', type: 'cor' },
    { key: '#0050c5', type: 'cor' },
    { key: '#082468', type: 'cor' },
    { key: '#192543', type: 'cor' },
] as const;