module.exports = {
    projects: [
        '<rootDir>/libs/stencil/design-system',
        '<rootDir>/libs/stencil/design-system/angular',
        '<rootDir>/libs/stencil/design-system/react',

        '<rootDir>/libs/stencil/lab-components/angular',

        '<rootDir>/apps/angular/dev-portal',
        '<rootDir>/libs/angular/dev-portal/docs',
        '<rootDir>/libs/angular/dev-portal/home',
        '<rootDir>/libs/angular/dev-portal/not-found',
        '<rootDir>/libs/angular/dev-portal/shared',

        '<rootDir>/apps/angular/feature-flag',
        '<rootDir>/libs/angular/feature-flag/features',
        '<rootDir>/libs/angular/feature-flag/auth',
        '<rootDir>/libs/angular/feature-flag/access-levels',

        '<rootDir>/apps/angular/finance-dash',
        '<rootDir>/libs/angular/finance-dash/recharges',

        '<rootDir>/apps/angular/ops-dash',
        '<rootDir>/libs/angular/ops-dash/help',
        '<rootDir>/libs/angular/ops-dash/login',
        '<rootDir>/libs/angular/ops-dash/users',
        '<rootDir>/libs/angular/ops-dash/variables',

        '<rootDir>/apps/angular/picpay-lab',
        '<rootDir>/libs/angular/picpay-lab/shared',

        '<rootDir>/apps/angular/picpedia',

        '<rootDir>/apps/angular/seller-panel',
        '<rootDir>/libs/angular/seller-panel/auth',
        '<rootDir>/libs/angular/seller-panel/services',
        '<rootDir>/libs/angular/seller-panel/helpers',
        '<rootDir>/libs/angular/seller-panel/shared',
        '<rootDir>/libs/angular/seller-panel/assets',
        '<rootDir>/libs/angular/seller-panel/login',
        '<rootDir>/libs/angular/seller-panel/settings',
        '<rootDir>/libs/angular/seller-panel/shipment',
        '<rootDir>/libs/angular/seller-panel/home',
        '<rootDir>/libs/angular/seller-panel/integrations',
        '<rootDir>/libs/angular/seller-panel/forgot-password',
        '<rootDir>/libs/angular/seller-panel/transactions',
        '<rootDir>/libs/angular/seller-panel/charge',
        '<rootDir>/libs/angular/seller-panel/extract',
        '<rootDir>/libs/angular/seller-panel/bank-accounts',
        '<rootDir>/libs/angular/seller-panel/credentials',

        '<rootDir>/apps/angular/seller-register',
        '<rootDir>/libs/angular/seller-register/assets',
        '<rootDir>/libs/angular/seller-register/form',
        '<rootDir>/libs/angular/seller-register/shared',

        '<rootDir>/libs/packages/event-tracking',
        '<rootDir>/libs/packages/features-flag',
        '<rootDir>/libs/packages/keycloak',

        '<rootDir>/libs/angular/shared/core/data-access',
        '<rootDir>/libs/angular/shared/core/notifications',
        '<rootDir>/libs/angular/shared/default-screens',
        '<rootDir>/libs/angular/shared/directives',
        '<rootDir>/libs/angular/shared/e2e',
        '<rootDir>/libs/angular/shared/helpers',
        '<rootDir>/libs/angular/shared/pipes',
        '<rootDir>/libs/angular/shared/services',
        '<rootDir>/libs/angular/shared/track-events',
        '<rootDir>/libs/angular/shared/validators',

        '<rootDir>/libs/ui/components',
        '<rootDir>/libs/ui/styles',
        '<rootDir>/libs/ui/layouts',

        '<rootDir>/apps/react/website',
        '<rootDir>/apps/react/webview',
        '<rootDir>/libs/packages/stencil-sass',
        '<rootDir>/libs/packages/sass-functions',
        '<rootDir>/libs/angular/picpedia/shared',
        '<rootDir>/libs/angular/picpedia/home',
        '<rootDir>/libs/angular/picpedia/assets',
        '<rootDir>/libs/angular/picpay-lab/dashboard',
        '<rootDir>/libs/react/webviews/cashback-calculator',
        '<rootDir>/libs/angular/seller-register/config',
        '<rootDir>/apps/nest/api-picpedia',
        '<rootDir>/libs/nest/api-picpedia/business-glossary',
        '<rootDir>/libs/angular/dev-portal/open-banking',
        '<rootDir>/libs/nest/api-picpedia/auth',
        '<rootDir>/libs/nest/api-picpedia/shared',
        '<rootDir>/apps/angular/growth-dash',
        '<rootDir>/libs/angular/growth-dash/shared',
        '<rootDir>/libs/angular/growth-dash/campaigns',
    ],
};
